version: "2"
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unused
formatters:
  enable:
    - gci
    - goimports
