builds:
  - goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X "main.airVersion={{.Version}}"
      - -s -w -X "main.goVersion={{.Env.GOVERSION}}"
archives:
  - id: tar.gz
    format: tar.gz
  - id: binary
    format: binary
