builds:
  - goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: darwin
        goarch: 386
    ldflags:
      - -s -w -X "main.airVersion={{.Version}}"
      - -s -w -X "main.goVersion={{.Env.GOVERSION}}"
    env:
      - CGO_ENABLED=0
archives:
  - id: tar.gz
    format: tar.gz
  - id: binary
    format: binary

brews:
  - name: air
    description: "Live reload for Go apps"
    homepage: "https://github.com/air-verse/air"
    repository:
      owner: air-verse
      name: homebrew-tap
    install: |
      bin.install "air"
    test: |
      system "#{bin}/air -v"
