steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [
        '-c',
        'DOCKER_BUILDKIT=1 docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME --build-arg TOKEN=$$TOKEN . --file=./Dockerfile' ]
    secretEnv:
      - 'TOKEN'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'linuxkit/binfmt:a17941b47f5cb262638cfb49ffc59ac5ac2bf334']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'my-builder']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', 'my-builder']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c','buildx build --platform $_DOCKER_BUILDX_PLATFORMS --build-arg TOKEN=$$TOKEN -t gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME . --push --file=./Dockerfile']
    secretEnv:
    - 'TOKEN'
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'
timeout: 6000s
options:
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'
substitutions:
  _DOCKER_BUILDX_PLATFORMS: "linux/amd64,linux/arm64"
availableSecrets:
  secretManager:
    - versionName: projects/searchspring-devops/secrets/machine-user-github-token/versions/latest
      env: 'TOKEN'